[project]
name = "anonxmusic"
version = "3.0.3"
description = "Telegram Group Calls Streaming bot with some useful features."
readme = ".github/README.md"
requires-python = ">=3.10"

dependencies = [
    "aiohttp>=3.11.11",
    "kurigram>=2.2.21",
    "pillow>=11.1.0",
    "psutil>=7.0.0",
    "py-tgcalls>=2.2.11",
    "py-yt-search>=0.6.2",
    "pymongo>=4.11.1",
    "pytgcrypto>=1.2.11",
    "python-dotenv>=1.0.1",
    "yt-dlp[default]>=2025.02.10",
    "uvloop>=0.21.0; sys_platform != 'win32'",
]
